version: '3.3'
services:
  market-bot:
    build:
      context: .
      dockerfile: ./TrafficMarketBot/Dockerfile
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_URLS=https://+:7089
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - 7089:7089
    networks:
      - default
    depends_on:
      - redis-cache
  
  redis-cache:
    image: redis/redis-stack-server:latest
    restart: always 
    networks:
      - default
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
