name: Deploy to Remote Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH
      run: |
        sudo apt update
        sudo apt install openssh-client -y

    - name: Deploy to server
      uses: easingthemes/ssh-deploy@v2.0.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote-user: ${{ secrets.REMOTE_USER }}
        remote-host: ${{ secrets.REMOTE_HOST }}
        remote-port: ${{ secrets.REMOTE_PORT }}
        source: '.' # Path to your project directory
        target: '/home/user/projects/my-project' # Path to the target directory on the remote server

    - name: Run project
      run: |
        ssh user@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} 'cd /home/user/projects/my-project && docker-compose up -d'
